const insumos = [
    {
      id: 1,
      name: "Fertilizante Orgánico",
      description: "Fertilizante Orgánico Mineral es la solución para potenciar tus cultivos.",
      price: 43000,
      images:["/Imagenes/Fertilizante_Org_Cabomag1.jpg",
            "/Imagenes/Fertilizante_Org_Cabomag2.jpg"],
    },
    {
      id: 2,
      name: "Insecticida Biológico",
      description: "Protección contra plagas sin dañar el medio ambiente.",
      price: 42000,
      images: ["/Imagenes/AGROBIOLOGICOS1.jpg",
        "/Imagenes/AGROBIOLOGICOS2.jpg",
        "/Imagenes/AGROBIOLOGICOS3.jpg"],
    },
    {
      id: 3,
      name: "Herramientas para Cultivo",
      description: "Kit de herramientas esenciales para el cultivo de café.",
      price: 150000,
      images: ["/Imagenes/kit1.jpg",
         "/Imagenes/kit2.jpg",
         "/Imagenes/kit3.jpg"],
    },
    {
      id: 4,
      name: "Abono Compostado",
      description: "Abono natural para fortalecer el crecimiento de las plantas.",
      price: 28000,
      images: ["/Imagenes/Abono1.jpg",
        "/Imagenes/Abono2.webp",
        "/Imagenes/Abono3.webp"],
    },
    {
      id: 5,
      name: "Malla Sombra 50%",
      description: "Malla para controlar la exposición al sol en cultivos sensibles.",
      price: 62000,
      images: ["/Imagenes/Malla1.jfif",
        "/Imagenes/Malla2.jpg",
        "/Imagenes/Malla3.jpg"],
    },
    {
      id: 6,
      name: "Sustrato Especial para Café",
      description: "Mejora el enraizamiento y nutrición de las plantas de café.",
      price: 33000,
      images: ["/Imagenes/Sustrato1.webp",
      "/Imagenes/Sustrato2.jpg"],
    },
    {
      id: 7,
      name: "Regadera de Alta Presión",
      description: "Ideal para el riego eficiente en plantaciones de café.",
      price: 45000,
      images: ["/Imagenes/Regadera1.webp",
      "/Imagenes/Regadera2.webp",
      "/Imagenes/Regadera3.webp"],
    },
    {
      id: 8,
      name: "Fungicida Ecológico",
      description: "Protege tus plantas contra hongos y enfermedades.",
      price: 38000,
      images: ["/Imagenes/Fungicida1.webp",
        "/Imagenes/Fungicida2.webp",
        "/Imagenes/Fungicida3.webp"],
    },
];

export default insumos;
